import { fetchGET, fetchPOST, buildPath } from './fetch';
import {
    DISMISS_ALERT,
    FETCH_FAILURE,
    FETCH_INIT,
    FETCH_PRODUCT_LINES,
    FETCH_SUCCESS,
    FETCH_WAREHOUSES,
    SET_ALERT,
    SET_TAB,
    UPDATE_SELECTION,
    PATH_WAREHOUSES,
    PATH_PRODUCT_LINES,
    PATH_CATEGORY,
    FETCH_CATEGORIES,
    PATH_COLLECTIONS,
    FETCH_COLLECTIONS,
    PATH_BASE_SKU_LIST,
    FETCH_BASE_SKU_LIST,
    PATH_STATUS_LIST,
    FETCH_STATUS_LIST,
    PATH_ITEMS,
    FETCH_ITEMS,
    PATH_SAVE_ITEM_STATUS,
    FETCH_ITEM,
    FETCH_POST_ITEM,
    SELECT_ITEM,
    SELECT_ALL_ITEMS,
    SET_COMPANY,
    PATH_CHECK_ADMIN_ROLE,
    FETCH_ADMIN_ROLE,
    SET_ROWS_PER_PAGE,
    SET_PAGE,
    SET_FILTER,
    TOGGLE_HIDE_ZERO_ON_HAND,
    TOGGLE_SHOW_ONLY_SELECTED, CLEAR_ALL_ITEMS
} from "./constants";

// export const RECEIVE_USER = 'RECEIVE_USER';


export const itemKey = (item) => ( `${item.ItemCode}:${item.WarehouseCode}`);

